In [1]:
import torch

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([ [1, 2, 3], 
                            [4, 5, 6]], dtype=torch.float32, requires_grad=True).to(device)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape) # 2 rows, 3 columns
print(my_tensor.requires_grad) # True

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', grad_fn=<ToCopyBackward0>)
torch.float32
cuda:0
torch.Size([2, 3])
True


## Other common Iniializiation methods

In [3]:
x = torch.empty(size = (3,3) )
print(x)
x = torch.zeros((3,3))
x = torch.randn((3,3))
x = torch.ones((3,3))
x = torch.eye(5,5 ) # identity matrix
x = torch.arange(start = 0, end = 10, step = 2) # [0, 2, 4, 6, 8]
x = torch.linspace(start = 0, end = 10, steps = 8)
x = torch.empty(size = (1,5)).normal_(mean = 0, std = 1) # normal distribution
x = torch.empty(size = (1,5)).uniform_(0, 1) # uniform distribution
x = torch.diag(torch.ones(3)) # torch eye (3,3)
x

tensor([[ 0.0000e+00,  0.0000e+00,  4.9500e-35],
        [ 3.0774e-41, -2.1119e-12,  3.0773e-41],
        [-1.5449e+22,  4.5605e-41,  1.4013e-45]])


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## How to initiliaze and conver tensors to other types (int, float, double)

In [4]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short()) # int 16
print(tensor.long()) # int 64
print(tensor.half()) # float 16
print(tensor.float()) # float 32
print(tensor.double()) # float 64



tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [5]:
import numpy as np
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor = torch.from_numpy(np_array)
print(tensor)
numpy_array = tensor.numpy()
print(numpy_array)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


## Tensor math

In [6]:
x = torch.tensor([1, 2 , 3])
y = torch.tensor([4, 5, 6])
z = x + y
print(z)

# division

z = torch.true_divide(x, y) # element-wise division
print(z)

# inplace operations

t = torch.zeros(3)
t.add_(x) # t += x

# exponentiation

z = x**2

# simple comparison
z = x > 0
z = x < 0
z

tensor([5, 7, 9])
tensor([0.2500, 0.4000, 0.5000])


tensor([False, False, False])

In [7]:
# matrix multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
z = torch.matmul(x1, x2) # 2, 3
print(z)
print(x1 @ x2) # matmul
z = x1.mm(x2) # 2, 3
print(z)

# matrix exponentiation

matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(2)) # square the matrix

# element wise mult

z  = x * y
print(z)

z = torch.dot(x, y) # dot product
print(z)


tensor([[1.6814, 1.0994, 1.2684],
        [1.8874, 1.1306, 1.5317]])
tensor([[1.6814, 1.0994, 1.2684],
        [1.8874, 1.1306, 1.5317]])
tensor([[1.6814, 1.0994, 1.2684],
        [1.8874, 1.1306, 1.5317]])
tensor([[1.8366, 1.7966, 0.8261, 1.2825, 0.7187],
        [0.9007, 1.5504, 0.8237, 0.9820, 0.8323],
        [0.6696, 0.5585, 0.4160, 0.4164, 0.2430],
        [1.4483, 1.4025, 0.6283, 1.2920, 0.6069],
        [1.4893, 1.2789, 0.6953, 1.1399, 0.6409]])
tensor([ 4, 10, 18])
tensor(32)


In [8]:
# batch matrix multiplication

batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m)) # (32, 10, 20)

tensor2 = torch.rand((batch, m, p)) # (32, 20, 30)

out_bmm = torch.bmm(tensor1, tensor2) # batch matrix multiplication
print(out_bmm.shape) # (32, 10, 30)

torch.Size([32, 10, 30])


In [9]:
# example of broadcasting

x1 = torch.rand((5, 5))
x2 = torch.rand((1,5 ))

z = x1 - x2 
z = x1 ** x2
print(z)
z = x1 * x2
print(z)  


tensor([[0.8262, 0.9599, 0.9572, 0.5381, 0.8701],
        [0.8381, 0.8423, 0.3500, 0.6770, 0.8101],
        [0.8328, 0.8893, 0.8611, 0.6633, 0.5362],
        [0.7733, 0.9493, 0.5371, 0.8064, 0.9964],
        [0.9139, 0.9546, 0.7428, 0.4817, 0.7819]])
tensor([[0.0538, 0.0622, 0.5106, 0.0439, 0.2700],
        [0.0586, 0.0158, 0.0827, 0.0911, 0.2245],
        [0.0565, 0.0280, 0.4217, 0.0854, 0.0773],
        [0.0363, 0.0554, 0.1795, 0.1588, 0.3833],
        [0.0982, 0.0587, 0.3227, 0.0309, 0.2048]])


In [ ]:
# Other Useful tensor operations

sum_x = torch.sum(x, dim = 0)
print(sum_x) # sum along the first dimension (columns)
values, indices = torch.max(x, dim = 0)
values, indices = torch.min(x, dim = 0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim = 0) # index of max value along the first dimension
z = torch.argmin(x, dim = 0) # index of min value along the first dimension
mean_x = torch.mean(x.float() , dim = 0)
z = torch.eq(x, y) # element-wise equality check 
sorted_y, indices = torch.sort(y, dim =0 ,descending = False)

z = torch.clamp(x , min = 0, max = 10) # clamp values to be >= 0, <= 10

x = torch.tensor([1, 0 , 1, 1, 1], dtype = torch.bool)
z = torch.any(x) 
print(z)
z = torch.all(x) 
print(z)




tensor(6)
tensor(True)
tensor(False)


## Tensor indexing

In [ ]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(x[0].shape) # first row x[0,:]

print(x[:, 0].shape)

print(x[2, 0: 10]) # first 10 elements of the 3rd row
x[0, 0] = 100

# Fancy indexing

x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices]) # get elements at indices 2, 5, 8

x = torch.rand((3,5))
print(x)
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols]) # get elements at (1,4) and (0,0)



torch.Size([25])
torch.Size([10])
tensor([0.7659, 0.6183, 0.0933, 0.6953, 0.9840, 0.7913, 0.1829, 0.6688, 0.6264,
        0.6282])
tensor([2, 5, 8])
tensor([[0.2372, 0.6838, 0.1223, 0.9515, 0.6496],
        [0.5821, 0.3096, 0.9567, 0.3157, 0.2213],
        [0.2065, 0.3886, 0.9969, 0.9913, 0.8121]])
tensor([0.2213, 0.2372])


In [ ]:
# Advanced indexing

x = torch.arange(10)
print(x[(x < 2) | (x > 7)]) # get elements less than 2 or greater than 7 (& )
print(x[x.remainder(2) == 0]) # get even numbers

# useful operations

print(torch.where(x > 5, x, x + 2)) # replace elements > 5 with 0
print(torch.tensor([0, 0, 1, 2,2, 3,4]).unique())
print(x.dim()) # number of dimensions 
print(x.numel()) # number of elements


tensor([0, 1, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([2, 3, 4, 5, 6, 7, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4])
1
10


## Reshaping


In [ ]:
import torch

# contiguous tensors

x = torch.arange(9)
x_3x3= x.view(3,3)
print(x_3x3) # view as 3x3 matrix
x_3x3 = x.reshape(3,3) # reshape to 3x3

# view and reshape are similar, but view requires the tensor to be contiguous in memory

y = x_3x3.t()
print(y.contiguous().view(9))


x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
print(torch.cat((x1, x2), dim=0).shape) # concatenate along the first dimension (rows)
print(torch.cat((x1, x2), dim=1).shape) # concatenate along the second dimension (columns)

z = x1.view(-1)
print(z.shape) 


batch = 64
x = torch.rand((batch, 2 , 5))
z = x.view(batch, -1)
print(z.shape) # (64, 10)

z = x.permute(0, 2, 1)
print(z.shape) # (64, 5, 2) # permute dimensions

x = torch.arange(10)
print(x.unsqueeze(0).shape) # add a new dimension at the beginning (1, 10)
print(x.unsqueeze(1).shape) # add a new dimension at index 1 (64, 1, 2, 5)

x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.squeeze(0).shape)

## expand



tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 10])
